### ISSUE TITLE
Minor spelling error in https://github.com/testflows/TestFlows-Core/blob/master/testflows/_core/__init__.py

### ISSUE THREAD

**Issue by martinm43** [testflows/TestFlows-Core#6]
Excellent library. One minor issue in the file mentioned above (https://github.com/testflows/TestFlows-Core/blob/master/testflows/_core/__init__.py)

Last line contains "lincenses" where there should be "licenses".

**Comment by vzakaznikov** [comment]
Thanks @martinm43 for reporting this issue!
